import{useEffect,useState}from"react";
import{supabase}from"./main";

const features=[["01","Private by design","Profiles, invitations and rooms are built around user-controlled privacy."],["02","Real connections","Discover people, build connections and move into private conversations when invited."],["03","Trust first","Verification, reporting, blocking and moderation belong in the foundation."]];

export default function App(){
 const[session,setSession]=useState(null),[mode,setMode]=useState(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[dob,setDob]=useState(""),[ageConfirmed,setAgeConfirmed]=useState(false),[terms,setTerms]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 const submit=async e=>{e.preventDefault();setBusy(true);setMessage("");
  if(mode==="signup"){if(!ageConfirmed||!terms){setMessage("You must confirm that you are 18+ and accept AMORA's terms and privacy requirements.");setBusy(false);return}
   const{error}=await supabase.auth.signUp({email,password,options:{data:{display_name:name,date_of_birth:dob,is_age_confirmed:true,terms_accepted:true,privacy_accepted:true}}});
   setMessage(error?error.message:"Account created. Check your email if confirmation is required, then sign in.");if(!error)setMode("signin");
  }else{const{error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?error.message:"Signed in.");}
  setBusy(false)
 };
 const signout=async()=>{await supabase.auth.signOut();setMessage("Signed out.");};
 return <div className="shell"><header><a className="brand" href="/"><b>A</b><span>AMORA</span></a><nav>{session?<><span className="signed">Signed in</span><button onClick={signout}>Sign out</button></>:<><button onClick={()=>{setMode("signin");setMessage("")}}>Sign in</button><button className="primary" onClick={()=>{setMode("signup");setMessage("")}}>Create account</button></>}</nav></header><main>
 <section className="hero"><div><small>ADULT SOCIAL & DATING</small><h1>Meet with intention.<br/><i>Connect privately.</i></h1><p>AMORA is being built for adults who want meaningful connections, private conversations and personal spaces designed around trust.</p><div className="actions"><button className="primary big" onClick={()=>setMode("signup")}>Join AMORA</button><button className="ghost big" onClick={()=>document.getElementById("foundation").scrollIntoView({behavior:"smooth"})}>Explore AMORA</button></div><label>18+ only · Consent, privacy and safety are fundamental.</label></div><div className="visual"><div className="glow one"/><div className="glow two"/><div className="room"><span>● Private room</span><strong>Only invited people enter.</strong></div></div></section>
 {session&&<section className="welcome"><small>YOUR AMORA ACCOUNT</small><h2>You're signed in.</h2><p>Your secure account foundation is connected. Discovery, connections, invitations and private rooms will be added on top of this account.</p></section>}
 <section id="foundation"><small>THE FOUNDATION</small><h2>Designed for trust before scale.</h2><p className="intro">Identity, privacy, communication, subscriptions and safety are being established as one system so AMORA can grow without rebuilding its core.</p><div className="grid">{features.map(([n,t,d])=><article key={n}><em>{n}</em><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 {mode&&<div className="modal"><div className="modal-card"><button className="close" onClick={()=>setMode(null)}>×</button><small>{mode==="signup"?"CREATE YOUR AMORA ACCOUNT":"WELCOME BACK"}</small><h2>{mode==="signup"?"Join AMORA":"Sign in"}</h2><form onSubmit={submit}>{mode==="signup"&&<><input required placeholder="Display name" value={name} onChange={e=>setName(e.target.value)}/><label className="field">Date of birth<input required type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label></>}<input required type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)}/><input required minLength="8" type="password" placeholder="Password (8+ characters)" value={password} onChange={e=>setPassword(e.target.value)}/>{mode==="signup"&&<div className="checks"><label><input type="checkbox" checked={ageConfirmed} onChange={e=>setAgeConfirmed(e.target.checked)}/> I confirm I am 18 or older.</label><label><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/> I accept AMORA's terms and privacy requirements.</label></div>}<button className="primary big" disabled={busy}>{busy?"Please wait…":mode==="signup"?"Create account":"Sign in"}</button></form>{message&&<p className="form-message">{message}</p>}<button className="switch" onClick={()=>setMode(mode==="signup"?"signin":"signup")}>{mode==="signup"?"Already have an account? Sign in":"Need an account? Create one"}</button></div></div>}
 {message&&!mode&&<div className="notice" role="status">{message}<button onClick={()=>setMessage("")}>×</button></div>}
 </main><footer><strong>AMORA</strong><span>Adult-only platform · Safety-first architecture</span></footer></div>
}